name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 'latest'
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dependencies
        run: poetry install --no-root

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Linter
        run: poetry run task lint

      - name: Run Formatter
        run: poetry run task formatter

      - name: Run Security Checks
        run: poetry run task security

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: poetry run task test

  build:
    name: Build Pipeline
    runs-on: ubuntu-latest
    needs:
      - static-analysis
      - unit-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Final Build Task
        run: echo "Build pipeline complete"
